module.exports = {
  at: { country: 'Austria', language: 'de', market: 'AT', super_region: 'europe' },
  au: { country: 'Australia', language: 'en', market: 'AU', super_region: 'north america' },
  be: { country: 'Belgium', language: 'nl', market: 'BE', super_region: 'europe' },
  ca: { country: 'Canada', language: 'en', market: 'CA', super_region: 'north america' },
  ch: { country: 'Switzerland', language: 'de', market: 'CH', super_region: 'europe' },
  cz: { country: 'Czechia', language: 'cs', market: 'CZ', super_region: 'europe' },
  de: { country: 'Germany', language: 'de', market: 'DE', super_region: 'europe' },
  dk: { country: 'Denmark', language: 'da', market: 'DK', super_region: 'europe' },
  es: { country: 'Spain', language: 'es', market: 'ES', super_region: 'europe' },
  fi: { country: 'Finland', language: 'fi', market: 'FI', super_region: 'europe' },
  fr: { country: 'France', language: 'fr', market: 'FR', super_region: 'europe' },
  gb: { country: 'United Kingdom', language: 'en', market: 'GB', super_region: 'europe' },
  gr: { country: 'Greece', language: 'el', market: 'GR', super_region: 'europe' },
  hr: { country: 'Croatia', language: 'hr', market: 'HR', super_region: 'europe' },
  hu: { country: 'Hungary', language: 'hu', market: 'HU', super_region: 'europe' },
  ie: { country: 'Ireland', language: 'en', market: 'IE', super_region: 'europe' },
  is: { country: 'Iceland', language: 'is', market: 'IS', super_region: 'europe' },
  it: { country: 'Italy', language: 'it', market: 'IT', super_region: 'europe' },
  lu: { country: 'Luxembourg', language: 'fr', market: 'LU', super_region: 'europe' },
  mx: { country: 'Mexico', language: 'es', market: 'MX', super_region: 'north america' },
  nl: { country: 'Netherlands', language: 'nl', market: 'NL', super_region: 'europe' },
  no: { country: 'Norway', language: 'no', market: 'NO', super_region: 'europe' },
  pl: { country: 'Poland', language: 'pl', market: 'PL', super_region: 'europe' },
  pr: { country: 'Puerto Rico', language: 'es', market: 'PR', super_region: 'north america' },
  pt: { country: 'Portugal', language: 'pt', market: 'PT', super_region: 'europe' },
  ro: { country: 'Romania', language: 'ro', market: 'RO', super_region: 'europe' },
  se: { country: 'Sweden', language: 'sv', market: 'SE', super_region: 'europe' },
  si: { country: 'Slovenia', language: 'sl', market: 'SI', super_region: 'europe' },
  us: { country: 'United States', language: 'en', market: 'US', super_region: 'north america' }
}
