module.exports = {
  ae: { country: 'United Arab Emirates', language: 'en', market: 'AE' },
  at: { country: 'Austria', language: 'de', market: 'AT' },
  au: { country: 'Australia', language: 'en', market: 'AU' },
  be: { country: 'Belgium', language: 'nl', market: 'BE' },
  ca: { country: 'Canada', language: 'en', market: 'CA' },
  ch: { country: 'Switzerland', language: 'de', market: 'CH' },
  cn: { country: 'China', language: 'zh', market: 'CN' },
  cz: { country: 'Czechia', language: 'cs', market: 'CZ' },
  de: { country: 'Germany', language: 'de', market: 'DE' },
  dk: { country: 'Denmark', language: 'da', market: 'DK' },
  es: { country: 'Spain', language: 'es', market: 'ES' },
  fi: { country: 'Finland', language: 'fi', market: 'FI' },
  fr: { country: 'France', language: 'fr', market: 'FR' },
  gb: { country: 'United Kingdom', language: 'en', market: 'GB' },
  gr: { country: 'Greece', language: 'el', market: 'GR' },
  hk: { country: 'Hong Kong', language: 'en', market: 'HK' },
  hr: { country: 'Croatia', language: 'hr', market: 'HR' },
  hu: { country: 'Hungary', language: 'hu', market: 'HU' },
  ie: { country: 'Ireland', language: 'en', market: 'IE' },
  il: { country: 'Israel', language: 'he', market: 'IL' },
  is: { country: 'Iceland', language: 'is', market: 'IS' },
  it: { country: 'Italy', language: 'it', market: 'IT' },
  jo: { country: 'Jordan', language: 'en', market: 'JO' },
  jp: { country: 'Japan', language: 'ja', market: 'JP' },
  kr: { country: 'Korea', language: 'ko', market: 'KR' },
  lu: { country: 'Luxembourg', language: 'fr', market: 'LU' },
  mo: { country: 'Macau', language: 'en', market: 'MO' },
  mx: { country: 'Mexico', language: 'es', market: 'MX' },
  my: { country: 'Malaysia', language: 'en', market: 'MY' },
  nl: { country: 'Netherlands', language: 'nl', market: 'NL' },
  no: { country: 'Norway', language: 'no', market: 'NO' },
  nz: { country: 'New Zealand', language: 'en', market: 'NZ' },
  pl: { country: 'Poland', language: 'pl', market: 'PL' },
  pr: { country: 'Puerto Rico', language: 'es', market: 'PR' },
  pt: { country: 'Portugal', language: 'pt', market: 'PT' },
  ro: { country: 'Romania', language: 'ro', market: 'RO' },
  se: { country: 'Sweden', language: 'sv', market: 'SE' },
  sg: { country: 'Singapore', language: 'en', market: 'sg' },
  si: { country: 'Slovenia', language: 'sl', market: 'SI' },
  th: { country: 'Thailand', language: 'th', market: 'TH' },
  tr: { country: 'Turkey', language: 'tr', market: 'TR' },
  tw: { country: 'Taiwan', language: 'zh', market: 'TW' },
  us: { country: 'United States', language: 'en', market: 'US' }
}
